//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synnduit.Logging.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Synnduit.Logging.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching destination system entities ... .
        /// </summary>
        internal static string CachingDestinationSystemEntities {
            get {
                return ResourceManager.GetString("CachingDestinationSystemEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes detected &amp; merged.
        /// </summary>
        internal static string ChangesDetectedAndMerged {
            get {
                return ResourceManager.GetString("ChangesDetectedAndMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating {0:#,##0} orphan mappings: .
        /// </summary>
        internal static string DeactivateOrphanMappings {
            get {
                return ResourceManager.GetString("DeactivateOrphanMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion progress.
        /// </summary>
        internal static string DeletionProgress {
            get {
                return ResourceManager.GetString("DeletionProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination system.
        /// </summary>
        internal static string DestinationSystem {
            get {
                return ResourceManager.GetString("DestinationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#,##0} entities cached..
        /// </summary>
        internal static string DestinationSystemEntitiesCachedFormat {
            get {
                return ResourceManager.GetString("DestinationSystemEntitiesCachedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 entity cached..
        /// </summary>
        internal static string DestinationSystemEntityCached {
            get {
                return ResourceManager.GetString("DestinationSystemEntityCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate detected, changes merged.
        /// </summary>
        internal static string DuplicateDetectedChangesMerged {
            get {
                return ResourceManager.GetString("DuplicateDetectedChangesMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate detected, no changes merged.
        /// </summary>
        internal static string DuplicateDetectedNoChangesMerged {
            get {
                return ResourceManager.GetString("DuplicateDetectedNoChangesMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#,##0} entities identified..
        /// </summary>
        internal static string EntitiesIdentifiedFormat {
            get {
                return ResourceManager.GetString("EntitiesIdentifiedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#,##0} entities loaded..
        /// </summary>
        internal static string EntitiesLoadedFormat {
            get {
                return ResourceManager.GetString("EntitiesLoadedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 entity identified..
        /// </summary>
        internal static string EntityIdentified {
            get {
                return ResourceManager.GetString("EntityIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 mapping loaded..
        /// </summary>
        internal static string EntityIdentifierMappingLoaded {
            get {
                return ResourceManager.GetString("EntityIdentifierMappingLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#,##0} mappings loaded..
        /// </summary>
        internal static string EntityIdentifierMappingsLoadedFormat {
            get {
                return ResourceManager.GetString("EntityIdentifierMappingsLoadedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 entity loaded..
        /// </summary>
        internal static string EntityLoaded {
            get {
                return ResourceManager.GetString("EntityLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity type.
        /// </summary>
        internal static string EntityType {
            get {
                return ResourceManager.GetString("EntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown.
        /// </summary>
        internal static string ExceptionThrown {
            get {
                return ResourceManager.GetString("ExceptionThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garbage Collection.
        /// </summary>
        internal static string GarbageCollection {
            get {
                return ResourceManager.GetString("GarbageCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifying entities to delete ... .
        /// </summary>
        internal static string IdentifyingEntitiesToDelete {
            get {
                return ResourceManager.GetString("IdentifyingEntitiesToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading source system entities ... .
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading entity identifier mappings ... .
        /// </summary>
        internal static string LoadingEntityIdentifierMappings {
            get {
                return ResourceManager.GetString("LoadingEntityIdentifierMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration.
        /// </summary>
        internal static string Migration {
            get {
                return ResourceManager.GetString("Migration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration progress.
        /// </summary>
        internal static string MigrationProgress {
            get {
                return ResourceManager.GetString("MigrationProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New entity created.
        /// </summary>
        internal static string NewEntityCreated {
            get {
                return ResourceManager.GetString("NewEntityCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes detected.
        /// </summary>
        internal static string NoChangesDetected {
            get {
                return ResourceManager.GetString("NoChangesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes merged.
        /// </summary>
        internal static string NoChangesMerged {
            get {
                return ResourceManager.GetString("NoChangesMerged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found in destination system.
        /// </summary>
        internal static string NotFoundInDestinationSystem {
            get {
                return ResourceManager.GetString("NotFoundInDestinationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#.00}%.
        /// </summary>
        internal static string ProgressFormat {
            get {
                return ResourceManager.GetString("ProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referred for manual deduplication.
        /// </summary>
        internal static string ReferredForManualDeduplication {
            get {
                return ResourceManager.GetString("ReferredForManualDeduplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing {0:#,##0} orphan mappings: .
        /// </summary>
        internal static string RemoveOrphanMappings {
            get {
                return ResourceManager.GetString("RemoveOrphanMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #,##0.
        /// </summary>
        internal static string ResultFormat {
            get {
                return ResourceManager.GetString("ResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment duration {0} seconds.
        /// </summary>
        internal static string SegmentDuration {
            get {
                return ResourceManager.GetString("SegmentDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment {0} out of {1}:.
        /// </summary>
        internal static string SegmentExecuting {
            get {
                return ResourceManager.GetString("SegmentExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string SegmentStartTime {
            get {
                return ResourceManager.GetString("SegmentStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string Skipped {
            get {
                return ResourceManager.GetString("Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source system.
        /// </summary>
        internal static string SourceSystem {
            get {
                return ResourceManager.GetString("SourceSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
